### ISSUE TITLE
No module named 'ordered_set'

### ISSUE THREAD

**Issue by haunetal1990** [skarndev/umodel_tools#14]
I would like to install the plugin in Blender 3.5, Blender 2.95 and Blender 3.6, but didn't work.

Traceback (most recent call last):
  File "C:\Users\WDAGUtilityAccount\Desktop\blender-3.5.0-windows-x64\blender-3.5.0-windows-x64\3.5\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "C:\Users\WDAGUtilityAccount\Desktop\blender-3.5.0-windows-x64\blender-3.5.0-windows-x64\3.5\scripts\addons\umodel_tools\__init__.py", line 32, in <module>
    from . import auto_load  # nopep8 pylint: disable=wrong-import-position
  File "C:\Users\WDAGUtilityAccount\Desktop\blender-3.5.0-windows-x64\blender-3.5.0-windows-x64\3.5\scripts\addons\umodel_tools\auto_load.py", line 6, in <module>
    from ordered_set import OrderedSet
ModuleNotFoundError: No module named 'ordered_set'

**Comment by skarndev** [comment]
Hi, you did not build your addon.
You can find ready to use builds on the Releases page. Or you can can follow the build instructions [here](https://skarndev.github.io/umodel_tools/installation.html#installing-from-sources) and build it yourself.
