### ISSUE TITLE
conflict with latest installed io_scene_psk_psa 5.0.5

### ISSUE THREAD

**Issue by harlantc** [skarndev/umodel_tools#16]
Minor issue with a conflict between having a pre-installed version of `io_import_scene_unreal_psa_psk` version 2.8.0 and the one coming from the third-party dependency. 

If you have installed `io_import_scene_unreal_psa_psk` and then try to enable `UModel_tool`, you'll get the error below. It would appear that the search path (does Blender python use PYTHONPATH? not familiar with it) gets picked up if you've installed the other addon independently (even if not enabled). 

Also, it seems the loading path and files are cached, as if you were to uninstall the conflicting addon, it won't fix things until after restarting Blender. Same for the opposite direction, installing the other addon and then `umodel_tool` does not cause an issue it seems until after restart.

```
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\modules\addon_utils.py", line 369, in enable
    mod.register()
  File "C:\Users\harley\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\umodel_tools\__init__.py", line 50, in register
    auto_load.init()
  File "C:\Users\harley\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\umodel_tools\auto_load.py", line 32, in init
    modules = get_all_submodules(Path(__file__).parent)
  File "C:\Users\harley\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\umodel_tools\auto_load.py", line 65, in get_all_submodules
    return list(iter_submodules(directory, directory.name))
  File "C:\Users\harley\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\umodel_tools\auto_load.py", line 70, in iter_submodules
    yield importlib.import_module("." + name, package_name)
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\harley\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\umodel_tools\asset_importer.py", line 8, in <module>
    from io_import_scene_unreal_psa_psk_280 import pskimport  # pylint: disable=import-error
ImportError: cannot import name 'pskimport' from 'io_import_scene_unreal_psa_psk_280' (C:\Users\harley\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\io_import_scene_unreal_psa_psk_280\__init__.py)
```

This is a minor issue, as one could rename the `io_import_scene_unreal_psa_psk` addon and circumvent this issue, or just uninstall it if you're not going to use it.

Versions:
Blender 3.6
io_import_scene_unreal_psa_psk 2.8.0
umodel_tools 1.0.4
Windows 11

**Comment by harlantc** [comment]
Actually, looking back, I'm not sure where my version of io_import_scene_unreal_psa_psk came from, I got it from a different location (though it says it's the same version number so this could still conflict is still important to note)

**Comment by Julz876** [comment]
This happened because of how the module was called. since the addon was packaged and not just a simple script
uses this instead:
from .third_party.io_import_scene_unreal_psa_psk_280 import pskimport  # pylint: disable=import-error
and this will separate them.
