### ISSUE TITLE
Blender 4.1 giving error and won't import anything else than map lights

### ISSUE THREAD

**Issue by KEDI103** [skarndev/umodel_tools#19]
It work with blender 3.6 but for blender 4.1 it won't 
Blender 3.6
![resim](https://github.com/skarndev/umodel_tools/assets/52115509/510223f6-cf02-4328-ae36-2331570e811b)
Blender 4.1
![resim](https://github.com/skarndev/umodel_tools/assets/52115509/1ddcfdf9-7097-4da3-b5f8-bc9a031767b9)

Heres console:

```
bpy.data.window_managers["WinMan"].addon_search = "un"
bpy.data.window_managers["WinMan"].addon_search = "umod"
bpy.context.space_data.recent_folders_active = 0
bpy.data.window_managers["WinMan"]. = '.tga'
Python: Traceback (most recent call last):
  File "C:\Users\B_CANSIN\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\umodel_tools\map_importer.py", line 643, in _import_map
    if (obj := self._load_asset(
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\B_CANSIN\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\umodel_tools\asset_importer.py", line 112, in _load_asset
    self._import_asset_to_library(context=context, asset_library_dir=asset_dir, asset_path=asset_path,
  File "C:\Users\B_CANSIN\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\umodel_tools\asset_importer.py", line 378, in _import_asset_to_library
    if not pskimport(filepath=pskx_path,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\B_CANSIN\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\io_import_scene_unreal_psa_psk_280.py", line 1051, in pskimport
    mesh_data.polygons.foreach_set("use_smooth", [True] * len(mesh_data.polygons))
    ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Mesh' object has no attribute 'use_auto_smooth'
bpy.ops.umodel_tools.import_unreal_map(filepath="G:\\fmodel_export\\Phoenix\\Content\\Environment\\Azkaban\\Maps\\Azkaban_Render_1_BuiltData.json", texture_format='.tga', files=[{"name":"Azkaban_Dungeon.json", "name":"Azkaban_Dungeon.json"}, {"name":"Azkaban_Dungeon_BuiltData.json", "name":"Azkaban_Dungeon_BuiltData.json"}, {"name":"Azkaban_Dungeon_FX.json", "name":"Azkaban_Dungeon_FX.json"}, {"name":"Azkaban_Dungeon_FX_BuiltData.json", "name":"Azkaban_Dungeon_FX_BuiltData.json"}, {"name":"Azkaban_Dungeon_Light.json", "name":"Azkaban_Dungeon_Light.json"}, {"name":"Azkaban_Dungeon_Tech.json", "name":"Azkaban_Dungeon_Tech.json"}, {"name":"Azkaban_Dungeon_Tech_BuiltData.json", "name":"Azkaban_Dungeon_Tech_BuiltData.json"}, {"name":"Azkaban_Render_1.json", "name":"Azkaban_Render_1.json"}, {"name":"Azkaban_Render_1_BuiltData.json", "name":"Azkaban_Render_1_BuiltData.json"}], directory="G:\\fmodel_export\\Phoenix\\Content\\Environment\\Azkaban\\Maps\\")

```

**Comment by skarndev** [comment]
The add-on has not yet been updated to a recent version of Blender. I will get back to it in the future.

**Comment by kokoadict** [comment]
how is that going? And what blender version should i use? I tried 3.4, 3.5, and 4,4. None worked
