### ISSUE TITLE
Error while importing json and umap

### ISSUE THREAD

**Issue by Midaco-YT** [skarndev/umodel_tools#20]
when i try to import map into blender 3.6 this error appear:

`Asset import had warnnings. Check console for details.
bpy.ops.umodel_tools.import_unreal_map(filepath="D:\\Games\\UEFN\\Output\\Exports\\Phoenix\\Content\\Environment\\Hogwarts\\SUB_AstronomyTower\\SUB_AstronomyTower_EXT.json", files=[{"name":"SUB_AstronomyTower_EXT.json", "name":"SUB_AstronomyTower_EXT.json"}], directory="D:\\Games\\UEFN\\Output\\Exports\\Phoenix\\Content\\Environment\\Hogwarts\\SUB_AstronomyTower\\")
`

and this for .umap

`Python: Traceback (most recent call last):
  File "C:\Users\trist\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\UE4_importer\umap.py", line 290, in execute
    LoadUMap(self.directory + file.name, cfg)
  File "C:\Users\trist\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\UE4_importer\umap.py", line 244, in LoadUMap
    with UAsset(filepath) as asset:
  File "C:\Users\trist\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\UE4_importer\uasset.py", line 523, in __enter__
    self.Read(self.read_all)
  File "C:\Users\trist\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\UE4_importer\uasset.py", line 493, in Read
    self.summary = summary = USummary(self)
  File "C:\Users\trist\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\UE4_importer\uasset.py", line 407, in __init__
    if sig != 0x9E2A83C1: raise Exception(f"Unknown signature: {sig:X}")
Exception: Unknown signature: 12E
`

can you help me pls

**Comment by skarndev** [comment]
The last error seems to be coming from a different add-on. I can't provide help with that. For the first one, please post the full import log.
