### ISSUE TITLE
errors on install

### ISSUE THREAD

**Issue by hannesdelbeke** [skarndev/umodel_tools#3]
hi, i m running in some errors on installation. 
i made a 1 click addon installer which installs the addon and requirements.txt, but i run in some issues:
![install_umodel-error](https://user-images.githubusercontent.com/3758308/231741188-4066f344-c44f-46c7-99f2-6e2453a7d89a.gif)

```
C:\Users\hanne\AppData\Local\Temp\plugget\blender\umodel-tools\latest\umodel-tools\umodel_tools
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\scripts\modules\addon_utils.py", line 335, in enable
    mod = __import__(module_name)
  File "C:\Users\hanne\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\modules\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\hanne\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\umodel_tools\__init__.py", line 32, in <module>
    from . import auto_load  # nopep8 pylint: disable=wrong-import-position
  File "C:\Users\hanne\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\modules\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\hanne\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\umodel_tools\auto_load.py", line 6, in <module>
    from ordered_set import OrderedSet
  File "C:\Users\hanne\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\modules\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'ordered_set'
```

```
  File "C:\Users\hanne\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\umodel_tools\utils.py", line 10, in <module>
    from . import preferences
  File "C:\Users\hanne\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\modules\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\hanne\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\umodel_tools\preferences.py", line 6, in <module>
    from . import game_profiles
  File "C:\Users\hanne\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\modules\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Users\hanne\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\umodel_tools\game_profiles\__init__.py", line 16, in <module>
    class GameHandler(t.Protocol):
  File "C:\Users\hanne\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\umodel_tools\game_profiles\__init__.py", line 56, in GameHandler
    ao_mix_node: bpy.types.ShaderNodeMix,
AttributeError: 'module' object has no attribute 'ShaderNodeMix'
```

**Comment by skarndev** [comment]
I assume you installed the add-on by cloning from git. In this case, you need to follow these install instructions: https://skarndev.github.io/umodel_tools/installation.html#installing-from-sources

If you just want to install, the Releases page has pre-built packages which are ready to use.
Also I noticed that you are on Blender 3.2. The minimum supported Blender version is 3.4.

**Comment by skarndev** [comment]
I also had a look at your installer. I am not sure my add-on is going to work with that in terms of installing requirements.txt. I supply my addons (only those that use external dependencies) with a lib vendoring script. The python packages are installed into umodel_tools/third_party directory which is added as a module search location. This way add-ons are self contained packages, avoiding any potential issues with package version collisions compared to when the dependencies are installed through pip into Blender's Python environment.

**Comment by hannesdelbeke** [comment]
thanks for explaining 🙏

**Comment by hannesdelbeke** [comment]
the addon install works with your addon.

it won't however handle collisions
> avoiding any potential issues with package version collisions
